<?php

namespace AppBundle\Repository;

/**
 * EsrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EsrRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function haveWaitingEsr($user){
        $qb = $this->createQueryBuilder('e');
        $qb->innerJoin('e.user', 'u')
        ->innerJoin('e.etat', 's')
        ->innerJoin('e.souscategorie', 's')
        ->where('s.libelle = :etatenattent')
        ->andwhere('s.codeSouscategorie IN (:categorie)')
        ->andWhere('u = :utilisateur')
        ->setParameter('etatenattent','Encours')
        ->setParameter('categorie','01')
        ->setParameter('utilisateur',$user);
        return count($qb->getQuery()->getResult())>0;
        
    }

    public function haveWaitingEi($user){
        $qb = $this->createQueryBuilder('e');
        $qb->innerJoin('e.user', 'u')
        ->innerJoin('e.etat', 's')
        ->innerJoin('e.souscategorie', 's')
        ->where('s.libelle = :etatenattent')
        ->andwhere('s.codeSouscategorie NOT IN (:categorie)')
        ->andWhere('u = :utilisateur')
        ->setParameter('etatenattent','Encours')
        ->setParameter('categorie','01')
        ->setParameter('utilisateur',$user);
        return count($qb->getQuery()->getResult())>0;
        
    }
    
    public function examensHaveSer($examenid){
        $qb = $this->createQueryBuilder('e');
        $qb->innerJoin('e.examen', 'ex');
        $qb->where('ex.id = :examenid');
        $qb->setParameter('examenid',$examenid);
        
        return count($qb->getQuery()->getResult())>0;
    }
    
   public function getWaitingEsr($user){
        $qb = $this->createQueryBuilder('e');
        $qb->innerJoin('e.user', 'u')
        ->innerJoin('e.etat', 's')
        ->where('s.libelle = :etatenattent')
        ->andWhere('u = :utilisateur')
        ->setParameter('etatenattent','Encours')
        ->setParameter('utilisateur',$user);
        
        return $qb->getQuery()->getResult();
        
    }
    
    public function getEsr($offset,$nbelement,$user,$etat,$seuil){
        $qb = $this->createQueryBuilder('e');
        $qb->innerJoin('e.souscategorie', 's'); 
        $qb->where('s.codeSouscategorie IN (:categorie)');
        $qb->leftJoin('e.user', 'u');        
        $qb->leftJoin('e.examen', 'x'); 
        $qb->leftJoin('x.region', 'r');
        $qb->leftJoin('r.regiondose', 'rd');
        $qb->leftJoin('rd.dose', 'd');
        $qb->andWhere('u = :utilisateur');
        //if($etat and $etat<>'null'){
        //    $qb->andWhere('e.etat = :etat');
        //}
        //if($seuil and $seuil<>'null'){
        //    $qb->andWhere('d.xrayTubeCurren2 > :seuil');
        //}
        $qb->setParameter('utilisateur',$user);
        //if($etat and $etat<>'null'){
        //    $qb->setParameter('etat',$etat);
        //}
        //if($seuil and $seuil<>'null'){
        //    $qb->setParameter('seuil',$seuil);
        //}
        $qb->setParameter('categorie','01');
        $qb->orderBy('e.id', 'DESC');
        $qb->setMaxResults($nbelement);
        $qb->setFirstResult($offset);
        return $qb->getQuery()->getResult();
        
    }
    public function getEi($offset,$nbelement,$user,$etat,$seuil){
        $qb = $this->createQueryBuilder('e');
        $qb->innerJoin('e.souscategorie', 's'); 
        $qb->leftJoin('e.user', 'u');        
        $qb->leftJoin('e.examen', 'x'); 
        $qb->leftJoin('x.region', 'r');
        $qb->leftJoin('r.regiondose', 'rd');
        $qb->leftJoin('rd.dose', 'd');        
        $qb->where('s.codeSouscategorie NOT IN (:categorie)');
        $qb->andWhere('s.codeSouscategorie IS NOT NULL');
        $qb->andWhere('u = :utilisateur');
        //dump($seuil);
        //dd($etat);
        //if($etat and $etat<>'null'){
        //    $qb->andWhere('e.etat = :etat');
        //}
        //if($seuil and $seuil<>'null'){
        //    $qb->andWhere('d.xrayTubeCurren2 > :seuil');
        //}        
        $qb->setParameter('utilisateur',$user);
        //if($etat and $etat<>'null'){
        //    $qb->setParameter('etat',$etat);
        //}
        //if($seuil and $seuil<>'null'){
        //    $qb->setParameter('seuil',$seuil);
        //}
        $qb->setParameter('categorie','01');
        $qb->orderBy('e.id', 'DESC');
        $qb->setMaxResults($nbelement);
        $qb->setFirstResult($offset);
        return $qb->getQuery()->getResult();
        
    }
}
    
    
