services:
 #   easy_dose.example:
 #       class: EasyDoseBundle\Example
 #       arguments: ["@service_id", "plain_value", "%parameter%"]
    easydose.security.controller:
        class: EasyDoseBundle\Controller\DefaultController
        arguments:
          - "@security.csrf.token_manager"
        calls:
          - [ setContainer,  ['service_container'] ]
        public: true

    authentication.handler.login_auth_success_handler:
        class:  EasyDoseBundle\Security\LoginSuccessHandler
        arguments:  ['@router', '@request_stack']

    userAction:
        class: EasyDoseBundle\Service\UserActionService
        arguments:
              - "@core.security"
              - "@doctrine"
    utils:
        class: EasyDoseBundle\Service\Utils
        arguments:
              - "@core.security"
              - "@doctrine"