# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        # other form themes
        - 'VichUploaderBundle:Form:fields.html.twig'
        - 'SonataCoreBundle:Form:datepicker.html.twig'
    globals:
        ckeditor_toolbar: %ckeditor_toolbar%
        locale: %locale%
        cpts: %cpt%
        taxos: %taxo%